Fix Timestamp defaultValue
mscheong01/krotoDC pull request #7
Opened 2023-05-22 04:20 UTC by davin111

Resolves #6

2023-05-30 01:44 UTC, mscheong01 requested changes

2023-05-30 01:44 UTC, mscheong01 commented on generator/src/main/kotlin/io/github/mscheong01/krotodc/predefinedtypes/HandledPreDefinedType.kt
> +        "Timestamp.getDefaultInstance().toLocalDateTime()",
Timestamp should be imported to fix the current error.
To do this, change defaultValue field type to CodeWithImports and add the import here

2023-06-08 08:27 UTC, davin111 commented
@mscheong01 I reflect your review. By the way, when I ran tests on my local (`./gradlew clean test`), I wasn't sure if ConversionTest was executed. Can you help me?

2023-06-08 12:52 UTC, mscheong01 commented
@davin111 Thanks! I'll take a look and let you know 😃

2023-06-08 13:22 UTC, mscheong01 approved these changes
@davin111 Thanks for your contribution 🥳. As for the tests, I'm experiencing something similar. Which is weird, since I'm sure it used to work fine. I've added #8 and will look into it when I get the chance.

2023-06-08 14:56 UTC, davin111 commented
@mscheong01 When are you planning to merge this PR? I'm not rushing you, just curious.

2023-06-09 02:29 UTC, merged